# Site Information
name:         "Pongstagr.am jQuery Plugin"
desc:         "is a jQuery plugin that lets you display your Instagram media to your website using Bootstrap Front-end styles and modal-plugin."

author:       "Pongstr - Philip Ordillo"
description:  "Pongstagr.am is a jQuery plugin that lets you display Instagram media to your website"
keywords:     "jquery, instagram, github, pongstr, ordillo, philip, pongstagram, pongstagr"

# Include/Exclude
exclude:      ['.gitignore', '*.sass-cache', 'scss', '*.txt', '*.rb', '*.sh', '_images', 'node_modules', 'bower_components', 'Gruntfile.js', 'package.json' ]

# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty
baseurl:      https://rogeriopradoj.github.io/pongstagr.am

# Server
destination:  _gh_pages
port:         4001

# Versions
repourl:     "https://github.com/rogeriopradoj/pongstagr.am/"
version:     "3.0.4"
download:    "https://github.com/rogeriopradoj/pongstagr.am/archive/v3.0.4.zip"
